Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIE_206.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Response.Headers.Add("Cache-Control", "no-cache, no-store, must-revalidate");
            Response.Headers.Add("Pragma", "no-cache");
            Response.Headers.Add("Expires", "0");
        }

        public void OnGetLogOut()
        {
            HttpContext.Session.Remove("UserFname");
            HttpContext.Session.Remove("Email");
            HttpContext.Session.Remove("UserType");
            HttpContext.Session.Remove("UserID");

            //Response.Headers.Add("Cache-Control", "no-cache, no-store, must-revalidate");
            //Response.Headers.Add("Pragma", "no-cache");
            //Response.Headers.Add("Expires", "0");

        }

    }
}

Pages/Shared/DashBoardLayout.cshtml
@*@if (Context.Session.GetString("UserType") == "A" || Context.Session.GetString("UserType") == "E" || Context.Session.GetString("UserType") == "DE")
*@{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>@ViewData["Title"] </title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="~/css/CharityWorkersView/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/CharityWorkersView/bootstrap-rtl.min.css">
        <script src="https://kit.fontawesome.com/49b2a74f1c.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/css/CharityWorkersView/imageupload.min.css">
        <link rel="stylesheet" href="~/css/CharityWorkersView/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/CharityWorkersView/slick.css">
        <link rel="stylesheet" href="~/css/CharityWorkersView/style.css">
        <link rel="stylesheet" href="~/css/CharityWorkersView/slick-theme.css">
        <link href="~/css/charityworkersview/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cairo:400,600,700">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

     
      

        <script src="https://kit.fontawesome.com/49b2a74f1c.js" crossorigin="anonymous"></script>
    </head>



    <body>

        <aside class="my-side">
            <div class="logo-main">
                <img src="~/images/CharityWorkersView/main-logo.png">
            </div>
            <ul class="aside-list">
                @{
                   // if (Context.Session.GetString("UserType") == "A")
                    {
                        <li id="link1"><a asp-page="/CharityWorkersView/statistics"><i class="fa fa-bar-chart fa-fw"></i> الاحصائيات </a></li>
                        <li id="link2"><a asp-page="/CharityWorkersView/Storage"><i class="fa fa-home fa-fw"></i> المخازن </a></li>
                        <li id="link4"><a asp-page="/CharityWorkersView/Tasks"><i class="fa fa-clock-o fa-fw"></i> المهام </a></li>
                        <li id="link6"><a asp-page="/CharityWorkersView/Employee"><i class="fa fa-address-card-o"></i> الموظفون </a></li>
                    <li id="link9"><a asp-page="/CharityWorkersView/DonatorsInfo"><i class="fas fa-handshake-o"></i>   بيانات المتبرعين  </a></li>
                        <li id="link12"><a asp-page="/CharityWorkersView/DonationsMenu"><i class="fas fa-handshake-o"></i>  قائمة التبرعات </a></li>
                        <li id="link10"><a asp-page="/CharityWorkersView/NeedyMenu"><i class="fa fa-heart-o"></i>  المستفيدين </a></li>
                        <li id="link11"><a asp-page="/CharityWorkersView/Volunteers"><i class="fa fa-user-plus fa-fw"></i>  المتطوعيين </a></li>
                        <li id="link7"><a asp-page="/CharityWorkersView/about"><i class="fa fa-laptop fa-fw"></i> عن الشركة </a></li>
                        <li id="link8"><a asp-page="/CharityWorkersView/contactus"><i class="fa fa-comments fa-fw"></i> معلومات التواصل </a></li>
                    }
                    //else if (Context.Session.GetString("UserType") == "E")
                    //{
                    //    <li id="link2"><a asp-page="/CharityWorkersView/Storage"><i class="fa fa-home fa-fw"></i> المخازن </a></li>
                    //    <li id="link4"><a asp-page="/CharityWorkersView/Tasks"><i class="fa fa-clock-o fa-fw"></i> المهام </a></li>
                    //    <li id="link10"><a asp-page="/CharityWorkersView/NeedyMenu"><i class="fa fa-heart-o"></i>  المستفيدين </a></li>

                    //}
                    //else if (Context.Session.GetString("UserType") == "DE")
                    //{
                    //     @*  <ul class="aside-list">

                    //    <li id="link1"><a asp-page="/CharityWorkersView/statistics"><i class="fa fa-bar-chart fa-fw"></i> الاحصائيات </a></li>
                    //    <li id="link2"><a asp-page="/CharityWorkersView/Storage"><i class="fa fa-home fa-fw"></i> المخازن </a></li>

                    //    <li id="link4"><a asp-page="/CharityWorkersView/Tasks"><i class="fa fa-clock-o fa-fw"></i> المهام </a></li>
                    //     <li id="link6"><a asp-page="/CharityWorkersView/Employee"><i class="fa fa-address-card-o"></i> الموظفون </a></li>
                    //    <li id="link9"><a asp-page="/CharityWorkersView/DonationsMenu"><i class="fas fa-handshake-o"></i>  المتبرعين </a></li>
                    //    <li id="link10"><a asp-page="/CharityWorkersView/NeedyMenu"><i class="fa fa-heart-o"></i>  المستفيدين </a></li>
                    //    <li id="link11"><a asp-page="/CharityWorkersView/Volunteers"><i class="fa fa-user-plus fa-fw"></i>  المتطوعيين </a></li>
                    //    <li id="link7"><a asp-page="/CharityWorkersView/about"><i class="fa fa-laptop fa-fw"></i> عن الشركة </a></li>
                    //    <li id="link8"><a asp-page="/CharityWorkersView/contactus"><i class="fa fa-comments fa-fw"></i> معلومات التواصل </a></li>
                    //    </ul>*@
                    //}

                }

            </ul>
        </aside>


        <div class="page-body">
            <nav class="navbar navbar-default my-nav">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                        <ul class="nav navbar-nav navbar-left">
                            <li class="dropdown">
                                <a href="#" class=" btn-notifcation notifcation-active"><i class="fa fa-bell"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle btn-acc" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">أحمد الجندي <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">الملف الشخصي</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">الاشعارات</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a asp-page="/Index" asp-page-handler="LogOut">تسجيل خروج</a></li>

                                </ul>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>


            <div class="page-content">
                @RenderBody()
            </div>
        </div>

        <script src="~/js/CharityWorkersView/jquery-1.12.0.min.js"></script>
        <script src="~/js/CharityWorkersView/bootstrap.min.js"></script>
        <script src="~/js/CharityWorkersView/Chart.min.js"></script>
        <script src="~/js/CharityWorkersView/utils.js"></script>
        <script src="~/js/CharityWorkersView/slick.min.js"></script>
        <script src="~/js/CharityWorkersView/imageupload.min.js"></script>
        <script src="~/js/CharityWorkersView/jquery.validate.min.js"></script>
        <script src="~/js/CharityWorkersView/script.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

        <script>
            window.onload = function () {
                var span = document.createElement('span');

                span.className = 'fa';
                span.style.display = 'none';
                document.body.insertBefore(span, document.body.firstChild);

                alert(window.getComputedStyle(span, null).getPropertyValue('font-family'));

                document.body.removeChild(span);
            };
        </script>
    </body>


    </html>


}
@*else
{
    Layout = "HomePagesLayout";
    @RenderBody()
}
*@

Pages/Shared/EmptyLayout.cshtml
@RenderBody()

Pages/Shared/HomePagesLayout.cshtml
<!DOCTYPE html>

<html class="no-js">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
    <meta name="author" content="FREEHTML5.CO" />
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <title>@ViewData["Title"] - CIE_206</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CIE_206.styles.css" asp-append-version="true" />




    <link rel="shortcut icon" href="~/template1/favicon.ico">
    <!-- Animate.css -->
    <link rel="stylesheet" href="~/template1/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/template1/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/template1/css/bootstrap.css">
    <!-- Superfish -->
    <link rel="stylesheet" href="~/template1/css/superfish.css">

    <link rel="stylesheet" href="~/template1/css/style.css">
    <link rel="stylesheet" href="~/template1/css/arabic_version.css" />

    <!-- Modernizr JS -->
    <script src="~/template1/js/modernizr-2.6.2.min.js"></script>



    <link rel="icon" href="~/template2/images/fevicon.png" type="image/gif" />
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/template2/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/template2/css/responsive.css">
    <link rel="stylesheet" href="~/template2/css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/template2/css/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <link href="~/template2/css/template2finalstyple.css" rel="stylesheet" />
</head>


<body>
    <div id="fh5co-wrapper">

        <div id="fh5co-page">


            <div class="header-top header-top-arabic">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 text-left fh5co-social">
                            <a href="https://www.facebook.com/a2elaty/" class="grow" target="_blank"><i class="icon-facebook2"></i></a>
                            <a href="https://www.facebook.com/a2elaty/" class="grow" target="_blank"><i class="icon-twitter2"></i></a>
                            <a href="https://www.facebook.com/a2elaty/" class="grow" target="_blank"><i class="icon-instagram2"></i></a>
                        </div>
                        <div class="col-md-6 col-sm-6 text-right fh5co-link">
                            @{
                                if (Context.Session.GetString("UserType") == null)
                                {
                                    <a class="fh5co-link-link" asp-page="/AnyUserView/LoginPage">تسجيل دخول | </a>
                                    <a class="fh5co-link-link" asp-page="/AnyUserView/SignUpPage">إنشاء حساب</a>
                                }
                                else
                                {
                                    string name = Context.Session.GetString("UserFname");
                                    <a class="fh5co-link-link" asp-page="/Index" asp-page-handler="LogOut">تسجيل خروج | </a>
                                    <a class="fh5co-link-link" asp-page="/AnyUserView/Personal_Info">@name أهلا</a>
                                    <a class="fh5co-link-link" asp-page="/AnyUserView/Personal_Info"><img src="../wwwroot/images/profile.jpg" /></a>
                             
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>


            <header id="fh5co-header-section" class="sticky-banner">
                <div class="container">
                    <div class="nav-header">
                        <a href="#" class="headeer-button js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
                        <h1 id="fh5co-logo">
                            <a asp-page="/Index">
                                <img src="~/images/logophoto.png" />
                            </a>
                        </h1>
                        <!-- START #fh5co-menu-wrap -->
                        <nav id="fh5co-menu-wrap" role="navigation">
                            <ul class="sf-menu" id="fh5co-primary-menu">
                                <li class="active"><a asp-page="/Index">الصفحة الرئيسية</a></li>
                                <li><a asp-page="/AnyUserView/DonatorPage" class="fh5co-sub-ddown">تبرع</a></li>
                                <li><a asp-page="/AnyUserView/VolunteerPage" class="fh5co-sub-ddown">تطوع</a></li>
                                <li><a asp-page="/AnyUserView/ContactPage">تواصل معنا</a></li>
                                <li><a asp-page="/AnyUserView/AboutPage">عنا</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </header>








            @RenderBody()





            <footer>
                <div id="footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 text-center">
                                <p class="fh5co-social-icons">
                                    <a href="https://www.facebook.com/a2elaty/" target="_blank"><i class="icon-twitter2"></i></a>
                                    <a href="https://www.facebook.com/a2elaty/" target="_blank"><i class="icon-facebook2"></i></a>
                                    <a href="https://www.facebook.com/a2elaty/" target="_blank"><i class="icon-instagram"></i></a>
                                    <a href="https://www.facebook.com/a2elaty/" target="_blank"><i class="icon-dribbble2"></i></a>
                                    <a href="https://www.facebook.com/a2elaty/" target="_blank"><i class="icon-youtube"></i></a>
                                </p>
                                <p>
                                    Copyright 2016 Free Html5 <a asp-page="/Index">Charity</a>. All Rights Reserved. <br>Made with
                                    <i class="icon-heart3"></i> by <a href="http://freehtml5.co/"
										target="_blank">Freehtml5.co</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>










        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/template1/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/template1/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/template1/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/template1/js/jquery.waypoints.min.js"></script>
    <script src="~/template1/js/sticky.js"></script>

    <!-- Stellar -->
    <script src="~/template1/js/jquery.stellar.min.js"></script>
    <!-- Superfish -->
    <script src="~/template1/js/hoverIntent.js"></script>
    <script src="~/template1/js/superfish.js"></script>

    <!-- Main JS -->
    <script src="~/template1/js/main.js"></script>



    <!-- Javascript files-->
    <script src="~/template2/js/popper.min.js"></script>
    <!-- sidebar -->

    <!-- javascript --> 
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>  
</body>
</html>